clone_folder: c:\projects\ubjsc
os: Visual Studio 2015

platform:
  - x64

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cmd: md build
  - cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Debug ..

test_script:
  - cmd: ctest
