image: mgdkn/ubjsc:0.5.5

pipelines:
  default:
    - step:
        script:
          - ./build.sh
          - ./check-coverage.sh
          - ./check-static.sh
          - ./check-leaks.sh
          - ./check-profile.sh
          - ./release.sh
