image: mgdkn/ubjsc:0.6.10.3

pipelines:
  default:
    - step:
        name: Build
        script:
          - ./build.sh
    - step:
        name: Code Coverage
        script:
          - ./check-coverage.sh
    - step:
        name: Static Analisys
        script:
          - ./check-static-complexity.sh
          - ./check-static-cppcheck.sh
          - ./check-static-markdown.sh
          - ./check-static-shellcheck.sh
          - ./check-static-vera++.sh
#          - ./check-static-py.sh
    - step:
        name: Leak Check
        script:
          - ./check-leaks.sh
  custom:
    profile:
      - step:
          script:
            - ./check-profile.sh
    test-stress:
      - step:
          script:
            - ./check-stress.sh
