image: mgdkn/ubjsc:0.6.10.1

pipelines:
  default:
    - step:
        script:
          - ./build.sh
          - ./check-coverage.sh
          - ./check-static.sh
          - ./check-leaks.sh
          - ./release.sh
  custom:
    profile:
      - step:
          script:
            - ./check-profile.sh
    test-stress:
      - step:
          script:
            - ./check-stress.sh
