image: mgdkn/ubjsc:v6

pipelines:
  default:
    - step:
        script:
          - ./build.sh
          - ./check-coverage.sh
          - ./check-static.sh
          - ./check-leaks.sh
          - ./release.sh
