image: mgdkn/ubjsc:0.5.6

pipelines:
  default:
    - step:
        script:
          - ./build-gcc.sh
          - ./build-clang.sh
          - ./check-coverage.sh
          - ./check-static.sh
          - ./check-leaks.sh
          - ./release.sh
